// <auto-generated />
using System;
using FashionizerProject.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FashionizerProject.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210629152748_x1")]
    partial class x1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FashionizerProject.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "phone",
                            Name = "Phones",
                            Url = "phones"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "watch",
                            Name = "Smartwatches",
                            Url = "smartwatches"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "aperture",
                            Name = "Earphones",
                            Url = "ear-phones"
                        });
                });

            modelBuilder.Entity("FashionizerProject.Shared.Edition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Editions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "64GB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "128GB"
                        },
                        new
                        {
                            Id = 3,
                            Name = "256GB"
                        },
                        new
                        {
                            Id = 4,
                            Name = "White"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nude"
                        });
                });

            modelBuilder.Entity("FashionizerProject.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The iPhone 12 and iPhone 12 Mini (stylized and marketed as iPhone 12 mini) are smartphones designed, developed, and marketed by Apple Inc.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8Qrz_OM7sCi3Rj_Z6i1uiVKpcAn1Oss5iviR2FkUQ9w1xnNlLbIPRY9povLrspM6xNqUVoE7q&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Apple iPhone 12 Red 128GB",
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The iPhone 12 and iPhone 12 Mini (stylized and marketed as iPhone 12 mini) are smartphones designed, developed, and marketed by Apple Inc.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8OTZkRMoSQMPy8Non_tDaKgZAysx3Lm67To0xpvVxNgbFLgfalvQrsB0s9aG3coUhjSGPPCg&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Apple iPhone 12 Blue 128GB",
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The iPhone 12 and iPhone 12 Mini (stylized and marketed as iPhone 12 mini) are smartphones designed, developed, and marketed by Apple Inc.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD3ODxjJaqY11RN31VZkuG9xyHRehQgW-jo5XAJfw6zDEHAV9tcARWtrgr1xQbi3yJDm6RoV8&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Apple iPhone 12 Gold 64GB",
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The sixth generation of the Apple Watch was revealed during the September 15, 2020 Time Flies Apple Event. Additional new features include a new S6 processor (that is up to 20% faster than the S4 and S5),[98] a brighter always-on display, a blood oxygen app that works with a new in-watch sensor and an always-on altimeter.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhQRINSKm8QQsa92OWjg0RVSEvdoGieYhsKqX9mJbuDbidnxsB1W611GwqDA&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "AppleWatch S6",
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Apple Watch SE only uses the S5 processor, does not have the ECG app and Blood Oxygen Sensor, and only comes with the 2nd generation Optical Heart Rate Sensor.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvzbfgTdpER5-rcDxRNb-wgfTDybd0U08fTy1NUpIGFLYCe8HFfZT9bnGSpd2COBFbPWvgIZk&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "AppleWatch Special Edition Nude",
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Apple Watch SE only uses the S5 processor, does not have the ECG app and Blood Oxygen Sensor, and only comes with the 2nd generation Optical Heart Rate Sensor.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStNAwkZtftUGIGQg0iMxVJkUq8uQ9_QlOokhRzOW9VVAg479qciaSF8MoivMU&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "AppleWatch Special Edition Black",
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " They are the same design as the first generation, but have updated features.[21] They include an H1 processor which supports hands-free 'Hey Siri', Bluetooth 5 connectivity. Apple also claims 50% more talk time and faster device connection times.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZgMnY0Hoxn1DiEq8iAGTdDnz81KD8Lnocml2CMAmb-e5ydSm4gDOQMGZ-C4lXHukcgsXpWxE&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Apple Airpods 2",
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The AirPods Pro use the H1 chip also found in second-generation AirPods that supports hands-free 'Hey Siri'. They have active noise cancellation, accomplished by microphones detecting outside sound and speakers producing precisely opposite 'anti - noise'.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjzRbltmbqjR3qvPHNPw0T6F53tttudpBly67ceHs4_7_cB7vUQOX2xvPk0cwntolBYy23vAc&usqp=CAc",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Apple AirPods Pro",
                            Views = 0
                        });
                });

            modelBuilder.Entity("FashionizerProject.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("EditionId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "EditionId");

                    b.HasIndex("EditionId");

                    b.ToTable("ProductVariant");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            EditionId = 1,
                            OriginalPrice = 3899.99m,
                            Price = 3899.99m
                        },
                        new
                        {
                            ProductId = 1,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 4499.99m
                        },
                        new
                        {
                            ProductId = 1,
                            EditionId = 3,
                            OriginalPrice = 5599.99m,
                            Price = 5299.99m
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 1,
                            OriginalPrice = 3899.99m,
                            Price = 3899.99m
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 4499.99m
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 3,
                            OriginalPrice = 5599.00m,
                            Price = 5299.66m
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 1,
                            OriginalPrice = 3899.99m,
                            Price = 3899.99m
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 4499.99m
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 3,
                            OriginalPrice = 5599.99m,
                            Price = 5299.99m
                        },
                        new
                        {
                            ProductId = 4,
                            EditionId = 5,
                            OriginalPrice = 0m,
                            Price = 1999.99m
                        },
                        new
                        {
                            ProductId = 4,
                            EditionId = 6,
                            OriginalPrice = 0m,
                            Price = 1999.99m
                        },
                        new
                        {
                            ProductId = 5,
                            EditionId = 6,
                            OriginalPrice = 1499.99m,
                            Price = 999.99m
                        },
                        new
                        {
                            ProductId = 6,
                            EditionId = 5,
                            OriginalPrice = 0m,
                            Price = 1499.99m
                        },
                        new
                        {
                            ProductId = 7,
                            EditionId = 4,
                            OriginalPrice = 0m,
                            Price = 649.99m
                        },
                        new
                        {
                            ProductId = 7,
                            EditionId = 5,
                            OriginalPrice = 0m,
                            Price = 649.99m
                        },
                        new
                        {
                            ProductId = 8,
                            EditionId = 4,
                            OriginalPrice = 0m,
                            Price = 1099.99m
                        },
                        new
                        {
                            ProductId = 8,
                            EditionId = 5,
                            OriginalPrice = 0m,
                            Price = 1099.99m
                        });
                });

            modelBuilder.Entity("FashionizerProject.Shared.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("FashionizerProject.Shared.Product", b =>
                {
                    b.HasOne("FashionizerProject.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FashionizerProject.Shared.ProductVariant", b =>
                {
                    b.HasOne("FashionizerProject.Shared.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionizerProject.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionizerProject.Shared.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
